/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Components;

import DBClasses.DB_query_invoice;
import Home.Cashier;
import Home.Cashier1;
import Home.Home;
import UIDesign.MajorFrame;
import UIDesign.Theme;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HASANKA
 */
public class Item extends javax.swing.JPanel implements ActionListener{

    private int id = 0;
    private String itemName = "";
    private String itemCode = "";
    private double price = 0.0;
    private double qty = 0.0;
    private ImageIcon imgIc = new ImageIcon();
    private String desc = "";
    
    DBClasses.DB_query_invoice db1 = new DB_query_invoice();

    
    JPanel jt = null;
    Cashier1 home;
    /**
     * Creates new form Item
     * @param jt
     */
    public Item(JPanel jt, Cashier1 home) {
        initComponents();
        setBackground(new Color(255,102,0));
        setOpaque(true);
        this.home = home;
        this.jt = jt;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 102, 0));

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Item Name | Qty 5 | 100");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton1.setOpaque(true);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    Vector v = new Vector();
    Cart cart = Cart.getInstance();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        if (v.contains(jButton1.getText())) {
//            Cart_Item ci = new Cart_Item(this, cart.getItemid());
//            v.set(v.indexOf(jButton1.getText())+1, Integer.parseInt(v.get(v.indexOf(jButton1.getText())+1).toString())+1);
//            cart.addToCart(ci, cart.getItemid());
        System.out.println(getItemCode());
            home.setCartPending(getItemCode());
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(Theme.btColorOrangeExit);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(new Color(0,153,204));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
         System.out.println(getItemCode());
            Cart_Item ci = new Cart_Item(null, this, cart.getItemid());
            cart.addToCart(ci, cart.getItemid(), imgIc);
            home.setCartPending(getItemCode());

    }//GEN-LAST:event_jButton1MouseClicked
        


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

    
    
    
    @Override
    public void actionPerformed(ActionEvent e) {
        System.out.println(getItemCode());
            Cart_Item ci = new Cart_Item(null, this, cart.getItemid());
            cart.addToCart(ci, cart.getItemid(), imgIc);
            home.setCartPending(getItemCode());

    }

    
    
        /**
     * @return the itemName
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * @param itemName the itemName to set
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
        jButton1.setText(itemName);
    }

    /**
     * @return the img
     */
    public ImageIcon getImg() {
        return imgIc;
    }

    /**
     * @param img the img to set
     */
    public void setImg(ImageIcon imgi) {
        this.imgIc = imgi;
        jButton1.setIcon(imgi);
    }

    /**
     * @return the itemCode
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * @param itemCode the itemCode to set
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    /**
     * @return the price
     */
    public double getPrice() {
        return price;
    }

    /**
     * @param price the price to set
     */
    public void setPrice(double price) {
        this.price = price;
    }

    /**
     * @return the qty
     */
    public double getQty() {
        return qty;
    }

    /**
     * @param qty the qty to set
     */
    public void setQty(double qty) {
        this.qty = qty;
    }

    /**
     * @return the id
     */
    public int getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * @return the desc
     */
    public String getDesc() {
        return desc;
    }

    /**
     * @param desc the desc to set
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }
    
}
